<a href="https://colab.research.google.com/github/xs2farooq/bth-ml-course/blob/main/bth_lecture_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

actual_height = np.array([150, 160, 170])
predicted_height = np.array([148, 165, 168])
print(actual_height)
print(predicted_height)

errors = actual_height - predicted_height
print(errors)

square_error = errors ** 2
print(square_error)

mean = np.mean(square_error)
print(mean)

[150 160 170]
[148 165 168]
[ 2 -5  2]
[ 4 25  4]
11.0
